spring.application.name=CustomsDutiesGtcs

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@112.220.114.131:1521/xe
spring.datasource.username=TEAM2_202508F
spring.datasource.password=java

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=60000

mybatis.configuration.auto-mapping-behavior=full
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=varchar
mybatis.type-aliases-package=kr.or.gtcs.**.dto
mybatis.mapper-locations=classpath:kr/or/gtcs/mybatis/mapper/*.xml

logging.level.p6spy=info
logging.level.kr.or.gtcs=info
logging.level.org.springframework=info
logging.level.org.springframework.web.servlet=info
logging.pattern.console=%highlight(%-5level) %cyan(%logger{1}) - %msg %n------------------------------------------%n

server.port=80
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=${user.home}/temp
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB
file.upload-path=${user.home}/gtcsfile

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.0-flash

spring.cloud.gcp.storage.project-id=gen-lang-client-0507541018
gcs.bucket.name=gtcs_ddit

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=wonhyo.970204@gmail.com
spring.mail.password=${GOOGLE_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

security.login-page=/login
security.logout-page=/logout

jwt.secret-key=1ezGLCgGzJ61ZjfXYZAQjMgKHeGMwrsQ

# Thymeleaf가 템플릿 존재 여부를 체크하고, 없으면 다음 리졸버(JSP)로 넘김
spring.thymeleaf.check-template=true
spring.thymeleaf.check-template-location=true

# Thymeleaf 뷰 리졸버의 우선순위 설정 (기본적으로 매우 낮게 설정하거나 조정)
spring.thymeleaf.view-names=exp/*,pdf/*

# 한국은행 api키
bok.api.key=${BOK_API_KEY}
